# Generated by Django 4.2.4 on 2023-09-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_artist_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist_profile',
            old_name='artist_desk',
            new_name='artist_desc',
        ),
    ]
