# Generated by Django 4.2.4 on 2023-09-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_artist_desk_artist_profile_artist_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('crowd_strength', models.PositiveSmallIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist_profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
