# Generated by Django 4.2.4 on 2023-09-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_book_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_artist',
            old_name='data',
            new_name='date',
        ),
    ]
