# Generated by Django 4.2.4 on 2023-09-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_data_book_artist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_artist',
            name='artist_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book_artist',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
